gitc

diff --git a/gitc b/gitc
--- a/gitc
+++ b/gitc
@@ -1,7 +1,13 @@
 #!/bin/bash
 
-if [ ! -d ".git" ]; then
-  echo "ERROR: not a git repo"
+#if [ ! -d ".git" ]; then
+  #echo "ERROR: not a git repo"
+  #exit 1
+#fi
+
+git status > /dev/null
+if [ $? -ne 0 ]; then
+  echo "gitc. This does not appear to be a git repo"
   exit 1
 fi
 
